# coding: utf-8
#
# Copyright 2014 The Oppia Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Common utilities for test classes."""

from __future__ import absolute_import  # pylint: disable=import-only-modules
from __future__ import unicode_literals  # pylint: disable=import-only-modules

import os
import re
import subprocess

import feconf
from scripts import common

import contextlib2
import psutil


def emulator_context(silent=True):
    """Sets up the Google Cloud Datastore emulator and returns an ExitStack to
    tear it down upon exiting the stack's context.

    Args:
        silent: bool. Whether to silence the outputs generated by the emulator.

    Example:
        with emulator_context(silent=True):
            run_backend_tests.main()
    """
    with contextlib2.ExitStack() as stack:
        if not os.path.exists(common.DATASTORE_EMULATOR_DATA_DIR):
            os.makedirs(common.DATASTORE_EMULATOR_DATA_DIR)

        stdout = (
            stack.enter_context(open(os.devnull, 'w')) if silent else
            subprocess.STDOUT)

        emulator_process = subprocess.Popen(
            [common.GCLOUD_PATH, 'beta', 'emulators', 'datastore', 'start',
             '--host-port', '%s:%d' % (
                 feconf.DATASTORE_EMULATOR_HOST,
                 feconf.DATASTORE_EMULATOR_PORT),
             '--data-dir', common.DATASTORE_EMULATOR_DATA_DIR,
             '--no-store-on-disk', '--consistency=1.0', '--quiet'],
            stdout=stdout, stderr=stdout)

        @stack.callback
        def tear_down_emulator_process(): # pylint: disable=unused-variable
            """Tears down the emulator process and all of its children."""
            root_proc = psutil.Process(emulator_process.pid)

            child_procs = root_proc.children(recursive=True)
            for proc in child_procs:
                proc.terminate()

            _, procs_still_running = psutil.wait_procs(child_procs, timeout=5)
            for proc in procs_still_running:
                proc.kill()

            root_proc.terminate()
            try:
                root_proc.wait(timeout=5)
            except psutil.TimeoutExpired:
                root_proc.kill()

        common.wait_for_port_to_be_open(feconf.DATASTORE_EMULATOR_PORT)

        exports = subprocess.check_output(
            [common.GCLOUD_PATH, 'beta', 'emulators', 'datastore', 'env-init',
             '--data-dir', common.DATASTORE_EMULATOR_DATA_DIR, '--quiet'])

        emulator_environ = dict(
            m.group(1, 2) for m in re.finditer('export (\w*)=(.*)', exports))
        emulator_environ['DATASTORE_USE_PROJECT_ID_AS_APP_ID'] = 'true'

        os.environ.update(emulator_environ)

        @stack.callback
        def tear_down_emulator_environ(): # pylint: disable=unused-variable
            """Tears down the emulator-specific environment variables."""
            for env in emulator_environ:
                del os.environ[env]

        return stack.pop_all()
